### ISSUE TITLE
issues after install

### ISSUE THREAD

**Issue by hoangnamitc** [voku/Arrayy#30]
HI,

after install Arrayy via composer:

![image](https://user-images.githubusercontent.com/7042462/57195781-b5e9b480-6f80-11e9-97ae-217f9c72d249.png)

How to fix it? tks

**Comment by voku** [comment]
maybe you have installed it with composer + php >= 7.0 but running the code the php < 7.0? 

PS: here you can see that the code is working on php >= 7.0 -> https://3v4l.org/bS7Ah

**Comment by hoangnamitc** [comment]
Oh, yes! 
my code is php version 5.6, but library Arrayy this not working php version be lower 7.x ?

**Comment by voku** [comment]
"A PHP array manipulation library. Compatible with PHP 7+" 

The code update from PHP 5 to PHP 7 should not be very hard, there are not that may BREAKING CHANGES (BC) -> https://www.php.net/manual/en/migration70.incompatible.php

And I would recommend to use a even more up-to-date version of php, because PHP 7.0 is already END OF LIFE (EOF) -> https://www.php.net/supported-versions.php
